### ISSUE TITLE
Solo tracks

### ISSUE THREAD

**Issue by Splines** [EnvelopSound/EnvelopForLive#104]
Hi there, thank you for these amazing free Max For Live devices ❤ I've just discovered the whole field of 3D sound and find it super interesting and am tinkering a bit to get to know the basics.

For the following, note that I'm working in the `Monitor 1 + 2` mode, i.e. I don't have any fancy 3D sound gear, just the usual headphones.

---

I'm wondering if there is a "trick" to solo tracks in Ableton that route their output to `Sends only`. **Right now, I always have to solo the track I want to listen to and the E4L Master track at the same time**. This could get annoying in a bigger project very quickly I guess.

It'd be amazing if a solution to this could even work if some tracks are sent to `Main` directly, e.g. for tracks where I don't want to apply any manual spatial process to them (I haven't found a E4L device that just routes my stereo signal as-is through everything. Even in the Omni Panner, the sound is very muffled. That's why I chose to sent them to `Main` directly).

---

Edit: To achieve this, maybe the `E4L Master Bus` device could detect if any other track (that has its routing set to `Sends Only`) is soloed and then additionally solo the track the `E4L Master BUs` device is currently living on? But I don't even know if that would be possible with Max4Live.

**Comment by mcslee** [comment]
The solo behavior is definitely a bit annoying. However, there is a reasonable workaround.

Instead of engaging the `Monitor 1+2` mode, you can instead manually assign Outputs 1/2 of the decoder to your hardware soundcard outputs.

<img width="443" alt="Screen Shot 2024-09-16 at 9 26 14 AM" src="https://github.com/user-attachments/assets/3ec8566f-7ed7-4bf1-8771-34218797d434">

<img width="445" alt="Screen Shot 2024-09-16 at 9 26 21 AM" src="https://github.com/user-attachments/assets/5278b91a-cb9c-4ea7-922f-e1209b3a6412">

If you configure it that way, then you can solo an individual track, the audio will continue to flow through the E4L Master device and out to your soundcard, without having to additionally solo the E4L Master Bus track.

> It'd be amazing if a solution to this could even work if some tracks are sent to Main directly

Yep, that should work fine. Tracks sent to Main as usual should still be easily solo-able.

> Edit: To achieve this, maybe the E4L Master Bus device could detect if any other track (that has its routing set to Sends Only) is soloed and then additionally solo the track the E4L Master BUs device is currently living on? But I don't even know if that would be possible with Max4Live.

That's in theory possible and I've thought about it, but I think it would be too potentially confusing and hacky, would also confuse situations where someone is *trying* to specifically solo the E4L Master Bus, etc. Could also have nasty interactions with MIDI control surfaces, etc. It feels like an overreach to me, so I've held off on that approach, as the above workaround is generally quite usable.

Hope this all helps, happy mixing!

**Comment by Splines** [comment]
Thank you for the fast reply and the exact solution I needed ;) Will try this out very soon.
