### ISSUE TITLE
Conflicts with previously installed odot library

### ISSUE THREAD

**Issue by attackrelease** [EnvelopSound/EnvelopForLive#16]
Upon first installing and opening the E4L objects, I was unable to get any of the objects in Live to successfully connect to the Envelop server. 

Removing previously installed odot objects from the Max folder and making sure only the ones that came packaged with the E4L folder were used successfully fixed the problem.

**Comment by ramagottfried** [comment]
Thanks -- yes, it's possible that you had an older version of odot installed which was missing some expressions used in E4L. I would think that Max would automatically load the externals in the local package first rather than looking for other installed packages, but apparently that's not the case.

As a test, could you install the most recent odot release and see if that fixes the problem?

**Comment by mcslee** [comment]
This issue should be resolved with the newest version of the software which bundles the latest odot externals for all platforms. Thanks for the report - and if you see this issue come back with the newest release of the software, please feel free to re-open the issue (or file a new one).
