### ISSUE TITLE
Native live FX

### ISSUE THREAD

**Issue by urantiani** [EnvelopSound/EnvelopForLive#55]
Where in the chains do I put Abletons Native Audio fx for them to be rendered into the B-Format file ? Or is it only possible to use E4L fx?

**Comment by mcslee** [comment]
Hi Sigurd - you can use Ableton audio effects if they come *before* the E4L panner devices. Since these devices only work on native stereo, they can't be used if they're placed after the E4L devices in the chain.

FYI - for general questions about using E4L, we also have an active Facebook group: https://www.facebook.com/groups/E4LUsers/
