### ISSUE TITLE
downmix multi channel audio

### ISSUE THREAD

**Issue by badgic** [EnvelopSound/EnvelopForLive#59]
Hi there, I'm trying to mixdown ( render/export) multi-channel audio with the binaural setting. What I hear in my headphones in binaural is accurate with my multi channel mix, but once I export it the recording of the mix is completely different.  What am I doing wrong?  Many thanks in advance for advice, envelop for Live is amazing!

**Comment by mcslee** [comment]
Hi there, there are two ways of exporting audio using E4L. 

(1) One is to use the recording feature of the E4L Master Bus, which is detailed here: https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Master-Bus#recording

This method makes a multi-channel recording of the raw Ambisonics format audio, with either 4 or 16 channels in B-Format or AmbiX encoding. If you do this, and play it back in headphones it will sound very weird as you'll be hearing raw, un-decoded Ambisonics audio.

(2) Use the normal export feature of Ableton Live. If you're doing this, make sure that the "Monitor 1+2" setting is engaged on the E4L Master Bus, with the binaural decoder selected. Ableton will then render the audio and capture the output sent to the Ableton Master bus. This will capture and record a stereo file of binaural audio.

Hope this clears it up? If not, let me know what process you were using to export the audio.

**Comment by badgic** [comment]
Thank you so much for your fast reply.

I’ve doing number 2... should be quite straight forward, don’t know why my mix is not accurate when exporting it, ..different levels than when I’m acuately mixing with headphones. 
will look again closely at routing.

http://www.junkerry.com

**Comment by badgic** [comment]
Hiya, my problem is that it renders the Spatial choreography/trajectories, but not the volume automation on the tracks, how come?

**Comment by mcslee** [comment]
Ah, I see. I think I know what the issue here might be. The E4L panning devices use the live.observer functionality to monitor changes to the channel faders and coordinate with the master bus. I suspect that when using Ableton's render feature, these live.observer events may not be triggered.

For a slightly annoying workaround - rather than automating the volume of the track, put either a Utility device or an EQ or anything with a gain control before the E4L panning device on the source track. Then automate the gain of the track from there, rather than using the track's volume fader.

It's not the most ideal, but I think this workaround should solve the problem you're seeing. Give it a shot and let me know if that works?

**Comment by badgic** [comment]
Many thanks for your help and advice. Tricky as I have so many tracks automated on the DAW. If there is any change in the future would you be kind enough to let me know, and is this something you might work on later within the patch - would that be a difficult adjustment to do in Max ? or if any more straightforward solution comes to your mind.. warmth

**Comment by badgic** [comment]
ok, will keep on eye on that thread. great work you guys have been doing with that device so far.

**Comment by mcslee** [comment]
Another suggestion here, by way of @willits 

Rather than using the Ableton export feature, what you can do is a perform a real-time recording of your mix onto another audio track in Ableton live.

- Set up a dummy audio track, call it "Render" or whatever you like
- Go to the track you have your E4L Master Bus on, change its output routing from "Master" to this "Render" track
- Set the "Render" track to "No Input" and to monitor "In"
- Arm the "Render" track for recording
- Hit record from the start of your project

This should get you a stereo recording of the binaural mix, onto this Render dummy track. And the volume automation should all work. You'll just have to wait a bit more patiently for the audio to be captured in real-time, rather than the sped-up Ableton export mode.

You can then just grab the recorded file out of your ableton project folder.

**Comment by badgic** [comment]
yes! sounds like a brilliant idea, will try that now big thanks

**Comment by badgic** [comment]
works like a charm, just had to export the "render" track the usual way after recording. For some reason can't listen to the recorded file from the project folder.

**Comment by Carnarts** [comment]
Hi, I just found this thread but I only figured out this workaround for the stereo mixdown issue after ages of experimentation and troubleshooting, I really think it should be mentioned in the wiki to save people some time. It's a great plugin though, just wish i found this thread before I started troubleshooting my stereo export from my track :)

**Comment by mcslee** [comment]
Just added a quick little tutorial to the Wiki about exporting Binaural mixes.

https://github.com/EnvelopSound/EnvelopForLive/wiki/Binaural-Export

**Comment by Carnarts** [comment]
That's great, yeah I don't think I trust the Ableton export any more and will probably always do a realtime recording.
