### ISSUE TITLE
questions about [e4l.live.once] abstraction and "E4L Master Bus"

### ISSUE THREAD

**Issue by ZucchiPfl** [EnvelopSound/EnvelopForLive#67]
Hi,

First, thank you for this amazing set of m4l, it is very useful and intuitive !

I am preparing a workshop for students about Max 4 Live and I would like to introduce how to manage surround into Live. I have a question about the [e4l.live.once] abstraction. If I understand correctly, the meaning of it is to prevent the action of the patchers after it when the device is loaded a second time, am I wrong ?

When I load the m4l "E4L Master Bus" for example the first time in my Live Set and I open the device into Max, if I check the outlet of [e4l.live.once] abstraction there is no data outputed. So that would mean that the patcher [p Initialize Tracks Outputs] is not supposed to do something. But, the track's name where my E4L Master Bus is loaded still change into "E4L Master Bus" which means the patcher [p Initialize Tracks Outputs] is processing besides there is no id input.

How do you really proceed here ? What am I missing ?

Pierre

**Comment by mcslee** [comment]
Hi Pierre - this is a good question and a tricky one for testing + development. Your understanding is correct - the e4l.live.once abstraction is designed to control an operation that is meant to occur just once, the very first time that *this instance* of the Max for Live device is instantiated and placed on an Ableton track. This performs "one-time-only" initializations, like automatically changing the name of a track, or modifying its output routing assignments. The initialization will not occur any subsequent time the device is loaded - the main example of this being when you load an Ableton project that has been previously saved.

It can be a bit hard to test and observe this behavior, because if you open the patch in Max from within Live, it will have *already* been initialized, and it won't run again. So, this is e4l.live.once behaving *correctly* - but you will be unable to trace from within Max when it actually *is* performing its operation that very first time. By the time you have "opened" the patcher in Max to explore it, you're already too late... Ableton had already run the initialization when you first added the patch.

As you describe, you can tell that obviously the code has actually run once, because your track name has been changed. The way you can see that it's working is as follows:
- Add E4L Master Bus device, see that track name automatically changes
- Rename the track manually to something else
- Save Ableton project
- Close Ableton project
- Re-open Ableton project

When you re-open the project, you will see that the track name doesn't change again. The code after e4l.live.once doesn't run this time, because the device has saved a parameter recording that it has already been run once.

It was quite fiddly to develop this properly. I have found initialization sequence and order to be one of the trickier parts of Max for Live development (and was why I created this abstraction to help with it).

I hope this makes sense! The short answer is that you have interpreted it correctly - the code after an e4.live.once device will only run ONCE ever (and you unfortunately won't be able to easily debug it, since it'll happen before you can open the Max UI).

If any of this wasn't clear, feel free to send any followup questions you have!
