### ISSUE TITLE
Convolution Reverb creating undo history

### ISSUE THREAD

**Issue by mcslee** [EnvelopSound/EnvelopForLive#92]
Even when no specific events or automation applied.

> There's nothing to screenshot, Just the convultion is making undo history without any parameters being automated. This is pretty common in some amatuer patches (Such as my own) and have had the issue with custom built stuff but normally only when you're moving parameters, so it's odd it's giving undo history when nothing is changing.
>
> I also experianced when mapping to a panner than when the mapping was deleted it was somehow still automating, this is using Live's LFO with the MAP or the multimap device.

Via [ally@yila.co.uk](mailto:ally@yila.co.uk)

**Comment by ramagottfried** [comment]
some more details would be helpful -- however, I did find one object that was creating undo history which was the locked dist display which is updated when linked with a panner device (which is the definitely the best way way to use the reverb I would say!). Setting the dist gui display to "hidden" in the parameter setup seems to fix the issue, since it is receiving the distance from the linked source.

The locked dist number is mainly for display or reloading the source distance, no need to include that in the history or stored state.

this it appears to be fixed to me, so closing now, but if anyone sees the issue again feel free to reopen.
