### ISSUE TITLE
Ear deafening ultra loud feedback sound | POTENTIAL HEARING LOSS/HAZARD

### ISSUE THREAD

**Issue by DeveeiveD** [EnvelopSound/EnvelopForLive#96]
While working on a set I somehow managed to have an arrangement of envelop devices in such a way that upon toggling the routing on one of the envelop devices somewhere an insane feedback loop occured and produced insanely loud feedback noise at max peak volume. I got my ears damaged and can still feel the pain after 6 hours.... This must be addressed in my opinion as this can be LETHAL. 

I will be attaching a screen recording of the almost narrowed down session and also provide an upload of the ableton live project as well to inspect if that helps.

Versions: 
- Ableton Live Suite 11 (11.2 Build: 2022-09-19_33f2245cd0)
- Max 8.3.1 (f487da5cc84)
- OSX Monterey 12.2.1 (i9 intel)
- envelop (https://github.com/EnvelopSound/EnvelopForLive/commit/b3f010f924975979f1245cbb320b06ccc2b43c40) (https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.0.1)

Project file (ableton native plugins only):  https://drive.google.com/file/d/10rNUZ7ngphC7_OGVGmCwN6hS5h2POavL/view?usp=share_link
Video demo (I tried turning down volume really low, but in the footage it's still could be considered loud - I STRONGLY suggest TURNING DOWN way LOWER on YT if you are going to watch it, don't be fooled by the quietness LOUD AT 2:04+): https://www.youtube.com/watch?v=RIrq9-83dd4 

As you can tell this feedback is so insanely loud that it can even be heard with utility @ -41.5 db on master.

P.S:

I could reproduce the behavior by reloading a project. However It does seem that it only happens under specific circumstances hence I include the specific project. Also note that there is no feedback routing of any kind within ableton itself, as I understand this is a certain asynchronousy in the envelop routing circuit.

**Comment by mcslee** [comment]
Very sorry you encountered this issue. Thanks for the detailed report and for the reproducible use case. I have just tested on my machine and was able to reproduce the issue - though in my case it only happens for an instant and then goes back to normal.

As a general rule, it's never recommended to change those routing selections while the Ableton session is playing. It changes the routing of multiple internal channels behind the scenes.

> However It does seem that it only happens under specific circumstances hence I include the specific project.

I am not shocked to hear this, I have seen some similar funny stuff with some of these routing APIs that seems like might be somehow dependent upon timing/CPU-load/project-config.

I may even just put a safeguard against this in the internal routing stuff, so that when these routing buttons are clicked, it stops the Ableton session from playing first, before changing the routing. On my system what I am seeing is that if I change routing while the transport is stopped, it updates fine with no glitching, but if I change routing while it's playing, it glitches when changing from Master to Chain, but not the other way around.

Can you test whether this is consistent with what you are seeing on your system? In particular, if you make these routing changes while the master transport is STOPPED, does that prevent glitching?

If that works on all systems, I think that may be the easiest immediate fix to address the safety issue here.

**Comment by mcslee** [comment]
Documenting my theory on why this *sometimes* happens, and why stopping the playback engine before changing routing may be the only solution.

Changing a device's output routing in the Max 4 Live API is done with two API calls. One to change routing_type (either a track, or the master bus) and one to change routing_channel (which input number on that routing object).

In development I found that I had to put a `deferlow` between these two calls. If I called them in immediate succession, the output routing channel numbers for the new output destination I had just chosen were not yet available. The `deferlow` call lets the `routing_type` take effect first, so that the `routing_channel` can then take effect.

I think the problem with this may be that sometimes this means the audio engine moves forward between these two calls, the `routing_channel` is not yet updated, and this can create loads of inputs feeding back.

This is just a theory. I do recall spending hours battling this routing code in initial development, trying to coordinate the interaction between these two. The API design clearly mirrors the routing selectors in the Ableton UI, e.g. in the second screenshot. You can imagine how this would also be a problem if trying to edit those in real-time via the UI while audio is playing... imagine if you want to route to the fifth device on a track, you have to change routing to that track first, to see its options, and then to the appropriate channel. But in between those two changes, you'll be creating feedback.

May just be inevitable that playback must be paused to change both settings before continuing playback. Will explore further.

<img width="1620" alt="Screen Shot 2023-02-17 at 2 41 18 PM" src="https://user-images.githubusercontent.com/597850/219685473-cc4ac282-8905-429d-8afc-8bfcca5534a8.png">

<img width="100" alt="Screen Shot 2023-02-17 at 3 01 56 PM" src="https://user-images.githubusercontent.com/597850/219690163-34d24a03-4114-4b15-8cbd-628301aee76a.png">

**Comment by DeveeiveD** [comment]
> Can you test whether this is consistent with what you are seeing on your system? In particular, if you make these routing changes while the master transport is STOPPED, does that prevent glitching?

From my testing (using the same project) I get the feedback out of control if there is any kind of signal going thru that danger chain (even if the signal is super quiet, so the logic in question is definitely active only when d/d(signal) != 0). Also feedback occurs regardless of the playback tick, i.e. even when paused.

**Comment by mcslee** [comment]
Okay thanks for checking that. Sounds like I may have to try another
approach where I suppress the device output entirely while the two routing
settings are being changed. This is probably safer anyways.

Le sam. 18 févr. 2023 à 21:40, DeveeiveD ***@***.***> a
écrit :

**Comment by ZeChArtiahSaher** [comment]
still no commits?

**Comment by mcslee** [comment]
This should be addressed in the next release via these two changes:
https://github.com/EnvelopSound/EnvelopForLive/commit/e08eba320935dcb3925c92bcf7962b38c1662956
https://github.com/EnvelopSound/EnvelopForLive/commit/51d1a0750b471016a0a7702317f12583b41296a4

**Comment by mcslee** [comment]
FYI - a pre-release with this fix + Apple Silicon support is now available for testing: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.3.4

**Comment by mcslee** [comment]
This should be resolved in the latest release:
https://github.com/EnvelopSound/EnvelopForLive/releases/
